spring:
  profiles:
    active: default
  main:
    show_banner: false
  freemarker:
    checkTemplateLocation: false
endpoints:
  jolokia:
    enabled: ${XD_JMX_ENABLED:true}
  jmx:
    enabled: ${XD_JMX_ENABLED:true}
    uniqueNames: true
  

XD_ANALYTICS: ${analytics:redis}
XD_TRANSPORT: ${xd.transport:${transport:redis}}
XD_HOME: ${xdHomeDir:..}
XD_JMX_ENABLED: true

xd:
  data:
    home: file:${XD_HOME}/data
  config:
    home: file:${XD_HOME}/config
  module:
    home: file:${XD_HOME}/modules
  ui:
    home: file:${XD_HOME}/spring-xd-ui/dist/
    allow_origin: http://xd.boostrack.com
  extensions:
       basepackages:
       locations: META-INF/spring-xd/ext
  container:
    groups: ${XD_CONTAINER_GROUPS:}
  messagebus:
    rabbit:
      default:
        ackMode:                   AUTO
            # Valid: AUTO (container acks), NONE (broker acks), MANUAL (consumer acks).
            # Upper case only.
            # Note: MANUAL requires specialized code in the consuming module and is unlikely to be
            # used in an XD application. For more information, see
            # http://docs.spring.io/spring-integration/reference/html/amqp.html#amqp-inbound-ack
        backOffInitialInterval:    1000
        backOffMaxInterval:        10000
        backOffMultiplier:         2.0
        concurrency:               1
        deliveryMode:              PERSISTENT
        maxAttempts:               3
        maxConcurrency:            1
        prefix:                    xdbus.
            # prefix for queue/exchange names so policies (ha, dle etc.) can be applied
        prefetch:                  1
        replyHeaderPatterns:       STANDARD_REPLY_HEADERS,*
        requestHeaderPatterns:     STANDARD_REQUEST_HEADERS,*
        requeue:                   true
        transacted:                false
        txSize:                    1
    redis:
      default:
        backOffInitialInterval:    1000
        backOffMaxInterval:        10000
        backOffMultiplier:         2.0
        concurrency:               1
        maxAttempts:               3
---

server:
  port: ${PORT:9393}
management:
  port: ${XD_MGMT_PORT:${PORT:9393}}
  contextPath: /management
---
# zk:
#   client:
#     connect: ${ZK_CLIENT_CONNECT:}

---
spring:
  profiles: rabbit
transport: rabbit
---

# XD admin profile
spring:
  profiles: admin
---

# XD container profile
spring:
  profiles: container
server:
  port: ${PORT:0}
management:
  port: ${XD_MGMT_PORT:${PORT:}}
  contextPath: /management
---

spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost/test
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
    validationQuery: select 1

---

spring:
  profiles: singlenode
  batch:
    initializer:
      enabled: true
  datasource:
    url: jdbc:hsqldb:hsql://${hsql.server.host:localhost}:${hsql.server.port:9101}/${hsql.server.dbname:xdjob}
    username: sa
    password:
    driverClassName: org.hsqldb.jdbc.JDBCDriver

transport: local
analytics: memory
embeddedHsql: true

---

# HSQL database configuration
 spring:
   datasource:
    url: jdbc:hsqldb:hsql://${hsql.server.host:localhost}:${hsql.server.port:9101}/${hsql.server.dbname:xdjob}
    username: sa
    password:
    driverClassName: org.hsqldb.jdbc.JDBCDriver
#ConnectionPoolSettings
    testOnBorrow: true
    validationQuery: select 1 from INFORMATION_SCHEMA.SYSTEM_USERS
    validationInterval: 30000
    maxActive: 100
    maxIdle: 100
    minIdle: 10
    initialSize: 0
    maxWait: 30000
    testOnReturn: false
    testWhileIdle: false
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 60000
    removeAbandoned: false
    removeAbandonedTimeout: 60
    logAbandoned: false
#Tomcat JDBC Enhanced Attributes
    validationInterval: 30000
    jmxEnabled: true
    fairQueue: true
    abandonWhenPercentageFull: 0
    maxAge: 0
    useEquals: true
    suspectTimeout: 0
    alternateUsernameAllowed: false
---

# Redis properties
spring:
  redis:
   port: 6379
   host: localhost
   pool.maxIdle: 8
   pool.minIdle: 0
   pool.maxActive: 8
   pool.maxWait: -1

---
# RabbitMQ properties
spring:
  rabbitmq:
   addresses: localhost:5672
   username: guest
   password: guest
   virtual_host: /
   useSSL: false
   sslProperties:

---
# Hadoop properties
# spring:
#   hadoop:
#    fsUri: hdfs://localhost:8020
